
test_train_split:
  test_size: 0.3
  random_state: 42
  shuffle: false

model: random_forest

models:
  random_forest: 
    n_estimators: 100
    criterion: gini
    max_depth: null
    min_samples_split: 2
    max_features: sqrt
  xgboost: 
    n_estimators: 100
    loss: log_loss
    learning_rate: 0.1
    criterion: friedman_mse
    max_depth: 3
    max_features: null
  
