
test_train_split:
  test_size: 0.3
  random_state: 42
  shuffle: false

model: xgboost

models:
  random_forest: 
    n_estimators: 100
    criterion: entropy
    max_depth: 3
    min_samples_split: 2
    max_features: sqrt
  xgboost: 
    n_estimators: 100
    loss: exponential
    learning_rate: 0.01
    criterion: squared_error
    max_depth: 3
    max_features: null
  
